# Generated by Django 4.2.3 on 2024-09-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('MEDICAL_EQUIPMENT', 'Medical Equipment'), ('PERSONNEL', 'Personnel'), ('FACILITIES', 'Facilities'), ('SUPPLIES', 'Supplies'), ('TRANSPORTATION', 'Transportation')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.departments')),
            ],
        ),
    ]
